-- ============================================================================
-- MIGRATION: Tabela perfil_permissoes + Seed Inicial
-- Data: 2026-03-03
-- Etapa 4 de 5 — Multi-tenant Admin Panel
-- Contexto: Define quais menus/telas cada perfil pode acessar no painel admin.
-- Perfis do painel admin:
--   super_admin  → tipo_pessoa = 8 (Administrador)
--   coordenador  → tipo_pessoa = 5
--   secretaria   → tipo_pessoa = 6
--   professor    → tipo_pessoa = 4
--   gestor_rh    → lms_empresa_usuarios.perfil = 'gestor_rh'
--   admin_curso  → lms_empresa_usuarios.perfil = 'admin_curso'
-- Não entram no painel: aluno (1), responsável (2), funcionário (3), colaborador
-- ============================================================================
BEGIN;

-- ============================================================================
-- 1. TABELA perfil_permissoes
-- ============================================================================
CREATE TABLE IF NOT EXISTS perfil_permissoes (
  id BIGSERIAL PRIMARY KEY,
  perfil VARCHAR(30) NOT NULL,
  menu_key TEXT NOT NULL,
  pode_visualizar BOOLEAN NOT NULL DEFAULT FALSE,
  pode_editar BOOLEAN NOT NULL DEFAULT FALSE,
  pode_excluir BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_perfil_permissoes UNIQUE (perfil, menu_key),
  CONSTRAINT ck_perfil_permissoes_perfil CHECK (
    perfil IN (
      'super_admin',
      'coordenador',
      'secretaria',
      'professor',
      'gestor_rh',
      'admin_curso'
    )
  )
);

COMMENT ON TABLE perfil_permissoes IS 'Mapa de permissões de acesso às seções do painel admin por perfil de usuário.
   menu_key corresponde à propriedade key de cada item em menuConfig.tsx.
   O perfil é derivado de tipo_pessoa (super_admin/coordenador/secretaria/professor)
   ou de lms_empresa_usuarios.perfil (gestor_rh/admin_curso).';

COMMENT ON COLUMN perfil_permissoes.menu_key IS 'Chave do item de menu (menuConfig.tsx key)';

COMMENT ON COLUMN perfil_permissoes.pode_visualizar IS 'Item aparece no menu / rota carrega';

COMMENT ON COLUMN perfil_permissoes.pode_editar IS 'Usuário pode criar e atualizar registros nessa tela';

COMMENT ON COLUMN perfil_permissoes.pode_excluir IS 'Usuário pode excluir/cancelar registros nessa tela';

CREATE INDEX IF NOT EXISTS idx_perfil_permissoes_perfil ON perfil_permissoes(perfil);

CREATE INDEX IF NOT EXISTS idx_perfil_permissoes_menu_key ON perfil_permissoes(menu_key);

-- Trigger de updated_at
CREATE TRIGGER trg_perfil_permissoes_set_updated_at BEFORE
UPDATE
  ON perfil_permissoes FOR EACH ROW EXECUTE FUNCTION fn_lms_set_updated_at();

-- ============================================================================
-- 2. RLS — apenas super_admin pode alterar; qualquer usuário autenticado
--    pode ler suas próprias permissões (via RPC fn_get_permissoes_perfil)
-- ============================================================================
ALTER TABLE
  perfil_permissoes ENABLE ROW LEVEL SECURITY;

-- Leitura aberta (filtro de perfil é feito na camada de aplicação / RPC)
DROP POLICY IF EXISTS pol_perfil_permissoes_select ON perfil_permissoes;

CREATE POLICY pol_perfil_permissoes_select ON perfil_permissoes FOR
SELECT
  USING (TRUE);

-- Escrita apenas para admin interno
DROP POLICY IF EXISTS pol_perfil_permissoes_manage ON perfil_permissoes;

CREATE POLICY pol_perfil_permissoes_manage ON perfil_permissoes FOR ALL USING (fn_lms_is_admin_interno());

-- ============================================================================
-- 3. SEED — Permissões por perfil
--    Colunas: perfil, menu_key, pode_visualizar, pode_editar, pode_excluir
--    Regra geral de excluir: somente super_admin = TRUE
--    Regra geral de editar : TRUE quando visualiza, exceto onde explicitado
-- ============================================================================
INSERT INTO
  perfil_permissoes (
    perfil,
    menu_key,
    pode_visualizar,
    pode_editar,
    pode_excluir
  )
VALUES
  -- ==========================================================================
  -- SUPER ADMIN — acesso irrestrito a tudo
  -- ==========================================================================
  (
    'super_admin',
    'home',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'alunos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'alunos-matriculados',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'alunos-inscritos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'ata-alunos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'exportar-frequencia',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'alunos-em-atraso',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'alterar-turmas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'alterar-mentoria',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'resetar-aluno',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'academico',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'avaliacoes',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'disciplinas-simulado',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'tipos-prova',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'provas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'digitacao-gabarito',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'digitacao-respostas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'redacoes',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'redacoes-alunos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'declaracoes',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'aulas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'agendamentos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'agendamentos-confirmados',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'reservas-temporarias',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'sala-de-aula',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'abertura-de-sala',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'material-aula',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'hierarquia-materiais',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'tipos-material',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'listar-tipos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'cadastrar-tipo',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'contratos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'contratos-pdf',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'gerar-parcelas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'gerar-contratos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'matriculas-nao-pagas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'contratos-cancelados',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'consultas-relatorios',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'relatorio-financeiro',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'relatorio-academico',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'financeiro',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'configuracao-taxas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'taxas-modalidade',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'relatorios-taxas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-dashboard-professor',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-empresas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-cursos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-modulos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-aulas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-exercicios',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-mapas-mentais',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-matriculas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-sessoes',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-painel-rh',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'lms-certificados',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'config',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'turmas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'disciplinas',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'professores',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'ano-letivo',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'cancelamentos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'cancelar-turma',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'descancelar-turma',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'pagamentos',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'baixa-pagamento',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'nota-fiscal',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'fontes-renda',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'controle-split',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'planos-professores',
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'super_admin',
    'planos-empresas',
    TRUE,
    TRUE,
    TRUE
  ),
  -- ==========================================================================
  -- COORDENADOR — gestão escolar completa, sem financeiro puro
  -- pode_excluir = FALSE (exclusões são responsabilidade do super_admin)
  -- ==========================================================================
  (
    'coordenador',
    'home',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'alunos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'alunos-matriculados',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'alunos-inscritos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'ata-alunos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'exportar-frequencia',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'coordenador',
    'alunos-em-atraso',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'coordenador',
    'alterar-turmas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'alterar-mentoria',
    TRUE,
    TRUE,
    FALSE
  ),
  -- resetar-aluno: NÃO para coordenador
  (
    'coordenador',
    'academico',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'avaliacoes',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'disciplinas-simulado',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'tipos-prova',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'provas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'digitacao-gabarito',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'digitacao-respostas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'redacoes',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'redacoes-alunos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'declaracoes',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'aulas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'agendamentos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'agendamentos-confirmados',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'reservas-temporarias',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'sala-de-aula',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'abertura-de-sala',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'material-aula',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'hierarquia-materiais',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'tipos-material',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'listar-tipos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'cadastrar-tipo',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'contratos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'contratos-pdf',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'gerar-parcelas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'gerar-contratos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'matriculas-nao-pagas',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'coordenador',
    'contratos-cancelados',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'coordenador',
    'consultas-relatorios',
    TRUE,
    FALSE,
    FALSE
  ),
  -- relatorio-financeiro: NÃO para coordenador
  (
    'coordenador',
    'relatorio-academico',
    TRUE,
    FALSE,
    FALSE
  ),
  -- financeiro / configuracao-taxas: NÃO para coordenador
  -- lms: NÃO para coordenador
  (
    'coordenador',
    'config',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'turmas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'disciplinas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'professores',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'coordenador',
    'ano-letivo',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'cancelamentos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'cancelar-turma',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'descancelar-turma',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'pagamentos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'baixa-pagamento',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'coordenador',
    'nota-fiscal',
    TRUE,
    FALSE,
    FALSE
  ),
  -- ==========================================================================
  -- SECRETARIA — contratos, alunos, declarações; sem acadêmico profundo
  -- pode_excluir = FALSE
  -- ==========================================================================
  (
    'secretaria',
    'home',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'alunos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'alunos-matriculados',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'alunos-inscritos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'ata-alunos',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'secretaria',
    'exportar-frequencia',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'secretaria',
    'alunos-em-atraso',
    TRUE,
    FALSE,
    FALSE
  ),
  -- alterar-turmas / alterar-mentoria / resetar-aluno: NÃO para secretaria
  (
    'secretaria',
    'academico',
    TRUE,
    FALSE,
    FALSE
  ),
  -- avaliacoes e sub-itens: NÃO para secretaria
  (
    'secretaria',
    'declaracoes',
    TRUE,
    TRUE,
    FALSE
  ),
  -- aulas / sala-de-aula / material-aula: NÃO para secretaria
  (
    'secretaria',
    'contratos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'contratos-pdf',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'gerar-parcelas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'gerar-contratos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'matriculas-nao-pagas',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'secretaria',
    'contratos-cancelados',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'secretaria',
    'consultas-relatorios',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'secretaria',
    'relatorio-financeiro',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'secretaria',
    'relatorio-academico',
    TRUE,
    FALSE,
    FALSE
  ),
  -- financeiro / configuracao-taxas: NÃO para secretaria
  -- lms: NÃO para secretaria
  -- config / turmas / disciplinas: NÃO para secretaria
  (
    'secretaria',
    'pagamentos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'baixa-pagamento',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'secretaria',
    'nota-fiscal',
    TRUE,
    FALSE,
    FALSE
  ),
  -- ==========================================================================
  -- PROFESSOR — foco em aulas, avaliações e alunos da sua turma
  -- pode_excluir = FALSE; pode_editar = FALSE em visualizações de leitura
  -- ==========================================================================
  (
    'professor',
    'home',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'professor',
    'alunos',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'professor',
    'alunos-matriculados',
    TRUE,
    FALSE,
    FALSE
  ),
  -- alunos-inscritos / ata-alunos: NÃO para professor
  (
    'professor',
    'exportar-frequencia',
    TRUE,
    FALSE,
    FALSE
  ),
  -- alunos-em-atraso / alterar-turmas / alterar-mentoria / resetar-aluno: NÃO
  (
    'professor',
    'academico',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'avaliacoes',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'disciplinas-simulado',
    TRUE,
    FALSE,
    FALSE
  ),
  -- tipos-prova: NÃO para professor
  (
    'professor',
    'provas',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'professor',
    'digitacao-gabarito',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'digitacao-respostas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'redacoes',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'redacoes-alunos',
    TRUE,
    TRUE,
    FALSE
  ),
  -- declaracoes: NÃO para professor
  (
    'professor',
    'aulas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'agendamentos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'agendamentos-confirmados',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'professor',
    'reservas-temporarias',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'sala-de-aula',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'abertura-de-sala',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'material-aula',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'hierarquia-materiais',
    TRUE,
    TRUE,
    FALSE
  ),
  -- tipos-material / listar-tipos / cadastrar-tipo: NÃO para professor
  -- contratos / financeiro / config: NÃO para professor
  (
    'professor',
    'lms',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'lms-dashboard-professor',
    TRUE,
    FALSE,
    FALSE
  ),
  -- lms-empresas / lms-matriculas / lms-sessoes / lms-painel-rh: NÃO
  (
    'professor',
    'lms-cursos',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'professor',
    'lms-modulos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'lms-aulas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'lms-exercicios',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'lms-mapas-mentais',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'professor',
    'lms-certificados',
    TRUE,
    FALSE,
    FALSE
  ),
  -- ==========================================================================
  -- GESTOR RH — acesso ao painel RH e gestão de usuários da empresa B2B
  -- pode_excluir = FALSE
  -- ==========================================================================
  (
    'gestor_rh',
    'home',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'gestor_rh',
    'lms',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'gestor_rh',
    'lms-painel-rh',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'gestor_rh',
    'lms-matriculas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'gestor_rh',
    'lms-sessoes',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'gestor_rh',
    'lms-certificados',
    TRUE,
    FALSE,
    FALSE
  ),
  -- ==========================================================================
  -- ADMIN CURSO — gerencia conteúdo LMS da empresa (cursos, módulos, aulas)
  -- pode_excluir = FALSE
  -- ==========================================================================
  (
    'admin_curso',
    'home',
    TRUE,
    FALSE,
    FALSE
  ),
  (
    'admin_curso',
    'lms',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'admin_curso',
    'lms-cursos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'admin_curso',
    'lms-modulos',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'admin_curso',
    'lms-aulas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'admin_curso',
    'lms-exercicios',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'admin_curso',
    'lms-mapas-mentais',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'admin_curso',
    'lms-matriculas',
    TRUE,
    TRUE,
    FALSE
  ),
  (
    'admin_curso',
    'lms-certificados',
    TRUE,
    FALSE,
    FALSE
  ) ON CONFLICT (perfil, menu_key) DO
UPDATE
SET
  pode_visualizar = EXCLUDED.pode_visualizar,
  pode_editar = EXCLUDED.pode_editar,
  pode_excluir = EXCLUDED.pode_excluir,
  updated_at = NOW();

-- ============================================================================
-- 4. RPC fn_get_permissoes_perfil — usada pelo frontend para carregar
--    as permissões do perfil do usuário logado em uma única chamada
-- ============================================================================
CREATE
OR REPLACE FUNCTION fn_get_permissoes_perfil(p_perfil TEXT) RETURNS TABLE (
  menu_key TEXT,
  pode_visualizar BOOLEAN,
  pode_editar BOOLEAN,
  pode_excluir BOOLEAN
) LANGUAGE SQL STABLE SECURITY DEFINER
SET
  search_path = public AS $ $
SELECT
  menu_key,
  pode_visualizar,
  pode_editar,
  pode_excluir
FROM
  perfil_permissoes
WHERE
  perfil = p_perfil
  AND pode_visualizar = TRUE
ORDER BY
  menu_key;

$ $;

COMMENT ON FUNCTION fn_get_permissoes_perfil(TEXT) IS 'Retorna todas as permissões ativas (pode_visualizar=true) de um perfil.
   Chamada pelo UserContext ao iniciar sessão para popular o estado de permissões.
   Exemplo: SELECT * FROM fn_get_permissoes_perfil(''coordenador'');';

COMMIT;