-- ============================================================
-- Migration: lms_planos (Planos controlados pelo super-admin)
-- Data: 2026-03-03
-- Descrição: Tabela de planos exibidos na landing page,
--            gerenciáveis via painel admin.
-- ============================================================
-- Tabela principal de planos
CREATE TABLE lms_planos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  slug VARCHAR(60) NOT NULL UNIQUE,
  descricao TEXT,
  preco_label TEXT NOT NULL DEFAULT 'Sob consulta',
  periodo VARCHAR(20) DEFAULT '',
  destaque BOOLEAN NOT NULL DEFAULT FALSE,
  ordem INTEGER NOT NULL DEFAULT 0,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  cta_label TEXT,
  cta_link TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  created_by BIGINT,
  updated_by BIGINT,
  deleted_by BIGINT
);

COMMENT ON TABLE lms_planos IS 'Planos exibidos na landing page do LMS, gerenciados pelo super-admin.';

-- Itens / benefícios de cada plano
CREATE TABLE lms_planos_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_plano BIGINT NOT NULL REFERENCES lms_planos(id) ON DELETE CASCADE,
  descricao TEXT NOT NULL,
  ordem INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE lms_planos_itens IS 'Itens/benefícios listados em cada plano da landing page.';

-- Índices
CREATE INDEX idx_lms_planos_ativo_ordem ON lms_planos (ativo, ordem);

CREATE INDEX idx_lms_planos_itens_plano ON lms_planos_itens (fk_id_plano, ordem);

-- RLS
ALTER TABLE
  lms_planos ENABLE ROW LEVEL SECURITY;

ALTER TABLE
  lms_planos_itens ENABLE ROW LEVEL SECURITY;

-- Leitura pública (landing page sem autenticação)
CREATE POLICY "lms_planos_select_public" ON lms_planos FOR
SELECT
  USING (
    ativo = TRUE
    AND deleted_at IS NULL
  );

CREATE POLICY "lms_planos_itens_select_public" ON lms_planos_itens FOR
SELECT
  USING (
    EXISTS (
      SELECT
        1
      FROM
        lms_planos p
      WHERE
        p.id = fk_id_plano
        AND p.ativo = TRUE
        AND p.deleted_at IS NULL
    )
  );

-- Escrita apenas para admin interno
CREATE POLICY "lms_planos_admin_all" ON lms_planos FOR ALL USING (fn_lms_is_admin_interno()) WITH CHECK (fn_lms_is_admin_interno());

CREATE POLICY "lms_planos_itens_admin_all" ON lms_planos_itens FOR ALL USING (fn_lms_is_admin_interno()) WITH CHECK (fn_lms_is_admin_interno());

-- Trigger de updated_at
CREATE
OR REPLACE FUNCTION fn_lms_planos_updated_at() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET
  search_path = public AS $ $ BEGIN NEW.updated_at := CURRENT_TIMESTAMP;

RETURN NEW;

END;

$ $;

CREATE TRIGGER tr_lms_planos_updated_at BEFORE
UPDATE
  ON lms_planos FOR EACH ROW EXECUTE FUNCTION fn_lms_planos_updated_at();

-- ============================================================
-- Seed: Dados iniciais
-- ============================================================
INSERT INTO
  lms_planos (
    nome,
    slug,
    descricao,
    preco_label,
    periodo,
    destaque,
    ordem,
    cta_label,
    cta_link
  )
VALUES
  (
    'Professor Starter',
    'professor-starter',
    'Para instrutores independentes começando a criar conteúdo.',
    'R$ 97',
    '/mês',
    FALSE,
    1,
    'Começar Agora',
    '/seja-professor'
  ),
  (
    'Professor Pro',
    'professor-pro',
    'Para professores que querem escalar e profissionalizar seus cursos.',
    'R$ 197',
    '/mês',
    TRUE,
    2,
    'Começar Agora',
    '/seja-professor'
  ),
  (
    'Empresa B2B',
    'empresa-b2b',
    'Mensalidade + split de pagamento. Cadastre professores e venda cursos com contratos anuais aos alunos.',
    'Sob consulta',
    '',
    FALSE,
    3,
    'Falar com Comercial',
    '/contato-empresa'
  );

INSERT INTO
  lms_planos_itens (fk_id_plano, descricao, ordem)
VALUES
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-starter'
    ),
    'Até 3 cursos publicados',
    1
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-starter'
    ),
    '50 alunos simultâneos',
    2
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-starter'
    ),
    '5 GB de armazenamento',
    3
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-starter'
    ),
    'Certificados automáticos',
    4
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-starter'
    ),
    'Split direto na sua conta',
    5
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-starter'
    ),
    'Suporte por e-mail',
    6
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-pro'
    ),
    'Até 10 cursos publicados',
    1
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-pro'
    ),
    '200 alunos simultâneos',
    2
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-pro'
    ),
    '25 GB de armazenamento',
    3
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-pro'
    ),
    'Exercícios e Flashcards',
    4
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-pro'
    ),
    'Split direto na sua conta',
    5
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'professor-pro'
    ),
    'Suporte prioritário',
    6
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'empresa-b2b'
    ),
    'Cursos ilimitados',
    1
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'empresa-b2b'
    ),
    'Múltiplos professores',
    2
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'empresa-b2b'
    ),
    'Contratos anuais com alunos',
    3
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'empresa-b2b'
    ),
    'Split automático de pagamento',
    4
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'empresa-b2b'
    ),
    'Matrículas em lote (CSV)',
    5
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'empresa-b2b'
    ),
    'Painel RH + Relatórios',
    6
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'empresa-b2b'
    ),
    'Gestão de licenças',
    7
  ),
  (
    (
      SELECT
        id
      FROM
        lms_planos
      WHERE
        slug = 'empresa-b2b'
    ),
    'Suporte premium',
    8
  );